app:
  repository: git.oteacher.org:5001/oteacher/main-service
  tag: "latest"
  pullPolicy: Always
  env:
    APP_NAME: "chat-service-service"
    APP_ENV: production
    APP_KEY: base64:la75J9DzrPe20uryTpx//YzAEzYlvk35dLkyxbg3wlg=
    APP_DEBUG: false
    APP_URL: http://main.stage.oteacher.org

    LOG_CHANNEL: single
    LOG_DEPRECATIONS_CHANNEL: null
    LOG_LEVEL: debug

    DB_CONNECTION: mysql
    DB_HOST: 10.0.0.15
    DB_PORT: 33740
    DB_DATABASE: prod_main
    DB_USERNAME: root
    DB_PASSWORD: "un[0KbMZmut9quwU"

    MONGO_DB_HOST: 10.0.0.55
    MONGO_DB_PORT: 27017
    MONGO_DB_DATABASE: prod_main
    MONGO_DB_USERNAME: amir
    MONGO_DB_PASSWORD: d55t1kq6tg4p1ca2

    BROADCAST_DRIVER: log
    CACHE_DRIVER: redis
    FILESYSTEM_DISK: s3
    QUEUE_CONNECTION: rabbitmq
    SESSION_DRIVER: redis
    SESSION_LIFETIME: 120

    RABBITMQ_HOST: rabbit-prod-rabbitmq.rabbit-prod
    RABBITMQ_PORT: 5672
    RABBITMQ_USER: user
    RABBITMQ_PASSWORD: YinFfHJxj2DEN78v
    RABBITMQ_VHOST: /
    RABBITMQ_QUEUE: main

    MEMCACHED_HOST: 127.0.0.1

    REDIS_HOST: cache-master
    REDIS_PASSWORD: null
    REDIS_PORT: 6379

    MAIL_MAILER: smtp
    MAIL_HOST: mailhog
    MAIL_PORT: 1025
    MAIL_USERNAME: null
    MAIL_PASSWORD: null
    MAIL_ENCRYPTION: null
    MAIL_FROM_ADDRESS: "hello@example.com"
    MAIL_FROM_NAME: "${APP_NAME}"

    AWS_ACCESS_KEY_ID: 14eb350d-5732-4d0d-8722-8e3acfd8434b
    AWS_SECRET_ACCESS_KEY: a9aea95d15c7e4f76a9a4c35ad87f352b1aaf6f26fbd1ab6b52273e94f14439f
    AWS_DEFAULT_REGION: "aws-global"
    AWS_BUCKET_DOCUMENTS: oteacher-documents
    AWS_DOCUMENT_URL: https://oteacher-documents.s3.ir-thr-at1.arvanstorage.ir/
    AWS_DOCUMENT_ENDPOINT: https://oteacher-documents.s3.ir-thr-at1.arvanstorage.ir
    AWS_USE_PATH_STYLE_ENDPOINT: true
    AWS_BUCKET_VIDEO: oteacher-videos
    AWS_VIDEO_URL: https://oteacher-videos.s3.ir-thr-at1.arvanstorage.ir/
    AWS_VIDEO_ENDPOINT: https://oteacher-videos.s3.ir-thr-at1.arvanstorage.ir
    COURSE_BUCKET: oteacher-courses
    AWS_COURSE_ENDPOINT: https://oteacher-courses.s3.ir-thr-at1.arvanstorage.ir

    PUSHER_APP_ID:
    PUSHER_APP_KEY:
    PUSHER_APP_SECRET:
    PUSHER_HOST:
    PUSHER_PORT: 443
    PUSHER_SCHEME: https
    PUSHER_APP_CLUSTER: mt1

    VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
    VITE_PUSHER_HOST: "${PUSHER_HOST}"
    VITE_PUSHER_PORT: "${PUSHER_PORT}"
    VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
    VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

    VHOST_FILE: vhost_dev.conf
    DOMAIN_HOST: temp.local.name
    DOMAIN_EMAIL: TEST@MAIL.COM
    USER_ID: 1000
    GROUP_ID: 1000
    L5_SWAGGER_GENERATE_ALWAYS: false
    L5_FORMAT_TO_USE_FOR_DOCS: json

    TIMING_SLICE: 30
    TIMING_SYSTEM_START_TIME: 03:00
    TIMING_SYSTEM_END_TIME: 23:30
    FREEZE_THRESHOLD: 10
    INVOICE_EXPIRY: 10

    SKYROOM_APIKEY: apikey-4-4613382-24727cd1224c9f1a0f96316cecd8661a
    SKYROOM_BASE_URL: https://class.oteacher.org/skyroom/api/

    ROOMEET_PHONE: 09380609996
    ROOMEET_PASSWORD: amin1991

    ALOCOM_BASEURL: https://pnlapi.alocom.co/api/v1/
    ALOCOM_USERNAME: '09129734152'
    ALOCOM_PASSWORD: 'majid1991'
    ALOCOM_SERVICE_ID: 57579

    THRESHOLD_HOLDING: 5
    DEFAULT_MEETING_PLATFORM: 1

    JWT_BLACK_LIST: false

    JWT_KEY: secret
    JWT_ALGO: HS256
    JWT_MAX_AGE: 300
    JWT_LEEWAY: 0
    JWT_SERVICE: 'r<7WH6K4J$>s+E3_*?xVf]'

    REDIRECT_AFTER_PAY: https://oteacher.org/after-pay

    PUBLIC_GATEWAY_URL: https://oteacher.org

    GATEWAY_URL: http://user-gateway-prod-laravel-helm.user-gateway-prod
    MAIN_URL: http://main-service-prod-laravel-helm.main-service-prod/
    PAYMENT_URL: http://payment-prod-laravel-helm.payment-prod/
    DISCOUNT_URL: http://discount-service-prod-laravel-helm.discount-service-prod/
    SENTRY_LARAVEL_DSN: http://06a6f34f5a244288b4fbd91c9d38e828@87.247.187.97:9000/20
    GATEWAY_QUEUE_NAME: gateway
    NOTIFICATION_QUEUE_NAME: 'notifications'
    SERVICE_ID: 1

    THRESHOLD_ABSENCE_TEACHER_TO: 1440
    THRESHOLD_ABSENCE_STUDENT_TO: 1440

  web:
    enabled: true
    web_server: "nginx"
    replicaCount: 1

  queueWorker:
    enabled: true
    replicaCount: 1

  schedule:
    enabled: true

redisQueue:
  architecture: standalone
  fullnameOverride: queue
  auth:
    enabled: false
redisCache:
  architecture: standalone
  fullnameOverride: cache
  auth:
    enabled: false

imagePullSecrets: [ { name: git.oteacher.org } ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: main.prod.oteacher.org
      paths:
        - path: /api
          pathType: Prefix
  tls: []
  #  - secretName: laravel-tls
  #    hosts:
  #      - laravel.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

