apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "golang-helm.fullname" . }}-env
  labels:
    {{- include "golang-helm.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.app.env }}
    {{ $key }}: "{{ $val }}"
  {{- end }}